### ISSUE TITLE
Broken after botguard integration

### ISSUE THREAD

**Issue by sn0opy** [SummerWish/ingress-exporter#11]
Niantic introduced Google's botguard protection to the Intel map. This prevents ingress-exporter to work after a few requests. 

IITCs current approach is to eval the code that's being sent with every request.

**Comment by sasha2002** [comment]
# node build/app.js
2015-01-19T08:47:25.544Z - info: [MungeDetector] Trying to extract munge data from ingress.com/intel.
2015-01-19T08:47:26.291Z - error: [Auth] Authentication failed. Please update the cookie.

But the cookie is OK

**Comment by sn0opy** [comment]
@sasha2002 you can stop using ingress-exporter after the last update. It's completely broken now, except you use a lot of stuff from IITC.

Regarding your issue: There's one check, which counts the felds in the returned entity object. Due to the introduction of botguard and especially the last update, the object now returns more than 2 elements. Thus it returns you that error. If you want to fix ingress-exporter, have fun porting this stuff: https://github.com/jonatkins/ingress-intel-total-conversion/commit/8d910a6f1e5bfad23eafb179060ce0404edc308e

**Comment by danizwam** [comment]
The issue with the new format has been discussed and solved in this thread: https://github.com/breeswish/ingress-exporter/issues/19

Unfortunately, i tried the script a minute ago and i get now a js error:

"Response" is not defined... 

/home/walter/ingress-exporter/build/lib/entity.js:84
  if (response.capturedTime != null) {
      ^
ReferenceError: response is not defined
    at Object.<anonymous> (/home/walter/ingress-exporter/build/lib/entity.js:84:7)
    at Object.<anonymous> (/home/walter/ingress-exporter/build/lib/entity.js:225:4)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/walter/ingress-exporter/build/app.js:37:3)
    at Object.<anonymous> (/home/walter/ingress-exporter/build/app.js:112:4)


Did i messed up my scripts by myself, or is it a new issue. can someone please test it?

**Comment by sn0opy** [comment]
@danizwam thanks, didn't see that issue actually.

Regarding your error: looks like you used "Response" with a capital "R" instead of a lowercase one.

**Comment by danizwam** [comment]
@sn0opy My fault ;) I kinda messed something up... rebuild from git source and everything works fine ;)

**Comment by sasha2002** [comment]
Sorry for bothersome but can somebody put this file into project or let me know where i can download it

**Comment by danizwam** [comment]
@sasha2002 Please look into the issue #19, there is all you need.

**Comment by danizwam** [comment]
@sasha2002 After altering my config.cson i run into the same error. Cookie was definetely correct. I probably messed something up with Notepad++. I delete my cson and recreated it with nano. That fixed it!

**Comment by sasha2002** [comment]
@danizwam can we talk under skype or email?
My mail : sashka2002@gmail.com
My skype : sasha200222

**Comment by sasha2002** [comment]
Broken again, new botguard modify
